name: combine_coverage
description: Utility for combining lcov files in a Dart or Flutter monorepo
version: 1.0.0
repository: https://github.com/verasana/combine_coverage
issue_tracker: https://github.com/verasana/combine_coverage/issues


environment:
  sdk: '>=2.18.4 <3.0.0'

executables:
  combine_coverage:

dependencies:
  args: ^2.3.1
  file: ^6.1.4
  glob: ^2.1.1
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0